# Site settings
name: Summer Serre Lab 2016
description: Summer 2016 at the Serre Lab.
author: Lindy Le
author_email: lindy_le@brown.edu
baseurl: /serre-lab # the subpath of your site, e.g. /blog
url: http://lindyle.github.io/ # the base hostname & protocol for your site
github_username: lindyle

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
