# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: Summer Serre Lab 2016
description: Summer 2016 at the Serre Lab.
author: Lindy Le
author_email: lindy_le@brown.edu
baseurl: /serre-lab # the subpath of your site, e.g. /blog
url: http://lindyle.github.io/ # the base hostname & protocol for your site
github_username: lindyle

# Build settings
markdown: kramdown
